### ISSUE TITLE
Why G for billions

### ISSUE THREAD

**Issue by KobaKhit** [jonasstein/sitools#1]
Just curious why G for billions?

**Comment by jonasstein** [comment]
G is the SI prefix for 10e9. It is very handy for physical units. One usage may be a frequency spectra, where you plot intensity in y and frequency on a log10 x axis. Ticks are labelled 1 kHz 10 kHz 100 kHz 1 MHz 10 MHz 100 MHz.
http://www.bipm.org/en/measurement-units/prefixes.html

**Comment by KobaKhit** [comment]
Right, makes sense. Thanks.
