### ISSUE TITLE
si2f prototype implementation

### ISSUE THREAD

**Issue by DarwinAwardWinner** [jonasstein/sitools#2]
I've implemented a prototype of si2f, the inverse of f2si. It works on vectors, and returns NA for elements that fail to parse. If you think this looks good, I can make a complete pull request including documentation and such.

```R
library(stringr)
library(rex)
si2f <- function(string, unit="") {
    sifactor <- c(1e-24, 1e-21, 1e-18, 1e-15, 1e-12, 1e-09, 1e-06,
                  0.001, 1, 1000, 1e+06, 1e+09, 1e+12, 1e+15, 1e+18, 1e+21,
                  1e+24)
    pre <- c("y", "z", "a", "f", "p", "n", "u", "m",
             "", "k", "M", "G", "T", "P", "E", "Z", "Y")

    rx <- rex(
        ## Leading whitespace
        start,
        zero_or_more(space),

        ## Capture a floating point number
        capture(
            ## Sign
            maybe(one_of("+", "-")),
            ## Integer part
            zero_or_more(digit),
            ## Decimal point
            maybe("."),
            ## Fractional part (or integer part when decimal is not
            ## present)
            one_or_more(digit),
            ## Exponential notation
            maybe(
                one_of("e", "E"),
                maybe(one_of("+", "-")),
                one_or_more(digit)
            )
        ),

        ## Space between number and unit
        zero_or_more(space),

        ## Capture SI prefix
        capture(maybe(one_of(pre))),

        unit,

        ## Trailing whitespace
        zero_or_more(space),
        end
    )

    m <- str_match(string, rx)
    base <- as.numeric(m[,2])
    p <- m[,3]
    fac <- sifactor[match(p, pre)]
    base * fac
}
```

**Comment by DarwinAwardWinner** [comment]
By the way, the latest version of this function can be found here: https://github.com/DarwinAwardWinner/rctutils/blob/master/R/si2f.R

**Comment by jonasstein** [comment]
Hi @DarwinAwardWinner 
Sorry, for the late reply. I am very glad about your improvements and looking forward to your pull request. Please do not forget to add your self the authors in https://github.com/jonasstein/sitools/blob/master/sitools/man/sitools-package.Rd#L19 and in the `thanks` list.

**Comment by DarwinAwardWinner** [comment]
How do you feel about adding more package dependencies? My implementation uses rex and stringr for the regular expression building and extraction, but if you don't want to add those dependencies, I can rewrite it using base R functions.
